import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-slate-950 text-slate-100 min-h-screen`}
      >
        <div className="fixed inset-0 -z-10 overflow-hidden">
          <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-slate-950 to-indigo-950" />
          <div className="absolute -left-20 top-10 h-72 w-72 rounded-full bg-purple-600/20 blur-[120px]" />
          <div className="absolute right-10 bottom-0 h-96 w-96 rounded-full bg-indigo-500/20 blur-[140px]" />
          <div className="absolute inset-0 bg-[radial-gradient(circle_at_20%_20%,rgba(255,255,255,0.06),transparent_35%),radial-gradient(circle_at_80%_0%,rgba(99,102,241,0.08),transparent_25%)]" />
        </div>

        <div className="relative mx-auto max-w-6xl px-6 py-10">
          <header className="mb-10 flex items-center justify-between gap-4 rounded-2xl border border-white/5 bg-white/5 px-6 py-4 shadow-lg shadow-indigo-900/40 ring-1 ring-white/10 backdrop-blur-lg">
            <Link href="/quizzes" className="flex items-center gap-3">
              <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-gradient-to-br from-indigo-500 via-purple-500 to-sky-400 text-lg font-semibold shadow-lg shadow-indigo-900/50">
                QB
              </div>
              <div>
                <p className="text-sm uppercase tracking-[0.2em] text-indigo-200/80">
                  Quiz Builder
                </p>
                <p className="text-lg font-semibold text-white">
                  Craft smarter quizzes
                </p>
              </div>
            </Link>

            <nav className="flex items-center gap-3 text-sm font-medium">
              <Link
                href="/quizzes"
                className="rounded-full border border-white/10 bg-white/5 px-4 py-2 text-slate-100 transition hover:border-indigo-400/60 hover:bg-white/10 hover:text-white hover:shadow-lg hover:shadow-indigo-900/50"
              >
                Browse quizzes
              </Link>
              <Link
                href="/create"
                className="rounded-full bg-gradient-to-r from-indigo-500 via-purple-500 to-sky-400 px-4 py-2 text-sm font-semibold text-white shadow-lg shadow-indigo-900/50 transition hover:translate-y-[-1px]"
              >
                New quiz
              </Link>
            </nav>
          </header>

          <main className="space-y-8">{children}</main>
        </div>
      </body>
    </html>
  );
}
